# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration version 2
Vagrant.configure("2") do |config|

  # Box bento/ubuntu-26.04
  config.vm.box = "bento/ubuntu-26.04"
  # Set hostname
  config.vm.hostname = "web-obb"
  # Disable automatic box update checking.
  config.vm.box_check_update = false
  # Forwarding port 8080 from host to VM port 80
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Fine-tune various backing providers for Vagrant.
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = 2
  end

  # Attaching 2 hard disks: disk-1 and disk-2 
  # This name is used as the filename when creating a virtual hard disk.
  (1..2).each do |i|
    config.vm.disk :disk, size: "1GB", name: "disk-#{i}"
  end

  # Enable provisioning with a shell script.
  # Add disks
  config.vm.provision "shell", path: "disks.sh"
  # Reboot to mount disks
  config.vm.provision 'shell', reboot: true, reset: true
  # Install nginx
  config.vm.provision "shell", path: "nginx.sh"

# Ansible do not support Windows host
#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "playbook.yml"
#  end

end
